apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: '*/2 * * * *'
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: resourcetracking-cronjob
              args: ['manage.py', 'harvest_tracertrak_feed']
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-uat
                      key: DATABASE_URL
                - name: TRACERTRAK_URL
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-uat
                      key: TRACERTRAK_URL
                - name: TRACERTRAK_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-uat
                      key: TRACERTRAK_AUTH_TOKEN
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-uat
                      key: SENTRY_DSN
                - name: SENTRY_ENVIRONMENT
                  value: 'uat'
