[tool.poetry]
name = "resource_tracking"
version = "1.3.0"
description = "DBCA internal corporate application to download and serve data from remote tracking devices."
authors = ["DBCA OIM <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
Django = "3.2.16"
psycopg2 = "2.9.4"
dbca-utils = "1.1.1"
django-extensions = "3.1.3"
django-dotenv = "1.4.2"
dj-database-url = "0.5.0"
gunicorn = "20.1.0"
django-tastypie = "0.14.3"
django-geojson = "2.12.0"
unicodecsv = "0.14.1"
requests = "2.28.1"
data-storage = {git = "https://github.com/dbca-wa/data-storage.git", rev = "v3.18"}
whitenoise = {version = "6.2.0", extras = ["brotli"]}

[tool.poetry.dev-dependencies]
ipython = "^7.31.1"
ipdb = "^0.13.4"
black = "22.10.0"

[build-system]
requires = ["poetry>=1.2.2"]
build-backend = "poetry.masonry.api"
