[tool.poetry]
name = "resource_tracking"
version = "1.5.4"
description = "DBCA corporate application to download and serve data from remote tracking devices."
authors = ["ASI <asi@dbca.wa.gov.au>"]

[tool.poetry.dependencies]
python = "^3.7"
Django = "2.2.16"
psycopg2-binary = "2.8.6"
dbca-utils = {git = "https://github.com/dbca-wa/dbca-utils", rev = "1.0.0"}
django-extensions = "3.0.8"
django-dotenv = "1.4.2"
dj-database-url = "0.5.0"
gunicorn = "20.0.4"
dj-static = "0.0.6"
django-tastypie = "0.14.3"
django-geojson = "2.12.0"
django-leaflet = "0.26.0"
unicodecsv = "0.14.1"
mixer = "6.1.3"
requests = "2.22.0"
Pillow = "7.2.0"
numpy = "1.19.2"
colour = "0.1.5"

[tool.poetry.dev-dependencies]
ipython = "^7.18.1"
ipdb = "^0.13.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
