[tool.poetry]
name = "resource_tracking"
version = "1.2.0"
description = "DBCA internal corporate application to download and serve data from remote tracking devices."
authors = ["DBCA OIM <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.8"
Django = "2.2.24"
psycopg2-binary = "2.8.6"
dbca-utils = {git = "https://github.com/dbca-wa/dbca-utils", rev = "1.0.0"}
django-extensions = "3.0.8"
django-dotenv = "1.4.2"
dj-database-url = "0.5.0"
gunicorn = "20.0.4"
dj-static = "0.0.6"
django-tastypie = "0.14.3"
django-geojson = "2.12.0"
unicodecsv = "0.14.1"
requests = "2.22.0"
data-storage = {git = "https://github.com/dbca-wa/data-storage.git", rev = "v3.18"}

[tool.poetry.dev-dependencies]
ipython = "^7.23.0"
ipdb = "^0.13.4"
black = "^21.7b0"

[build-system]
requires = ["poetry>=1.1.6"]
build-backend = "poetry.masonry.api"
