[tool.poetry]
name = "resource_tracking"
version = "1.3.5"
description = "DBCA internal corporate application to download and serve data from remote tracking devices."
authors = ["DBCA OIM <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.10"
django = "3.2.21"
psycopg2 = "2.9.6"
dbca-utils = "1.1.6"
python-dotenv = "1.0.0"
dj-database-url = "1.0.0"
gunicorn = "21.2.0"
django-extensions = "3.2.3"
django-tastypie = "0.14.5"
django-geojson = "2.12.0"
unicodecsv = "0.14.1"
whitenoise = {version = "6.5.0", extras = ["brotli"]}
azure-storage-blob = "12.17.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.13.0"
ipdb = "^0.13.13"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.masonry.api"
