[tool.poetry]
name = "resource_tracking"
version = "1.4.11"
description = "DBCA internal corporate application to download and serve data from remote tracking devices."
authors = ["DBCA OIM <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
django = "4.2.11"
psycopg = {version = "3.2.1", extras = ["binary", "pool"]}
dbca-utils = "2.0.2"
python-dotenv = "1.0.1"
dj-database-url = "2.2.0"
gunicorn = "22.0.0"
django-extensions = "3.2.3"
django-tastypie = "0.14.7"
django-geojson = "4.1.0"
unicodecsv = "0.14.1"
whitenoise = {version = "6.7.0", extras = ["brotli"]}
azure-storage-blob = "12.20.0"
sentry-sdk = {version = "2.10.0", extras = ["django"]}

[tool.poetry.group.dev.dependencies]
ipython = "^8.26.0"
ipdb = "^0.13.13"
pre-commit = "^3.7.1"
mixer = "^7.2.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.masonry.api"
