[tool.poetry]
name = "resource_tracking"
version = "1.3.2"
description = "DBCA internal corporate application to download and serve data from remote tracking devices."
authors = ["DBCA OIM <asi@dbca.wa.gov.au>"]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.9"
django = "3.2.19"
psycopg2 = "2.9.5"
dbca-utils = "1.1.6"
django-extensions = "3.2.1"
dj-database-url = "1.0.0"
gunicorn = "20.1.0"
django-tastypie = "0.14.3"
django-geojson = "2.12.0"
unicodecsv = "0.14.1"
data-storage = {git = "https://github.com/dbca-wa/data-storage.git", rev = "v3.18"}
whitenoise = {version = "6.3.0", extras = ["brotli"]}
python-dotenv = "0.21.0"

[tool.poetry.group.dev.dependencies]
ipython = "^8.13.0"
ipdb = "^0.13.13"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.masonry.api"
