apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: "* * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resourcetracking-cronjob
            args: ["manage.py", "harvest_tracplus"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: DATABASE_URL
            - name: TRACPLUS_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: TRACPLUS_URL
