apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: '* * * * *'
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: resourcetracking-cronjob
              args: ['manage.py', 'harvest_tracking_email', '--device-type', 'mp70']
              envFrom:
                - secretRef:
                    name: resourcetracking-env-uat
