apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-harvest-email
spec:
  schedule: '*/2 * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: resourcetracking-harvest-email
            image: ghcr.io/dbca-wa/resource_tracking:1.3.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - python manage.py harvest_tracking_email --device-type iriditrak && python
              manage.py harvest_tracking_email --device-type dplus && python manage.py
              harvest_tracking_email --device-type spot && python manage.py harvest_tracking_email
              --device-type mp70
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DATABASE_URL
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_HOST
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_PASSWORD
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_USER
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-harvest-dfes
spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 120
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: resourcetracking-harvest-email
            image: ghcr.io/dbca-wa/resource_tracking:1.3.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - python manage.py harvest_dfes_feed
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DATABASE_URL
            - name: DFES_PASS
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_PASS
            - name: DFES_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_URL
            - name: DFES_USER
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_USER
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-harvest-tracplus
spec:
  schedule: '* * * * *'
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 120
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: resourcetracking-harvest-email
            image: ghcr.io/dbca-wa/resource_tracking:1.3.7
            imagePullPolicy: IfNotPresent
            command:
            - /bin/bash
            - -c
            - python manage.py harvest_tracplus
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DATABASE_URL
            - name: TRACPLUS_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: TRACPLUS_URL
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
