apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
nameSuffix: -prod
resources:
  - ../../base
  - cronjobs/harvest-dfes
  - cronjobs/harvest-email-dplus
  - cronjobs/harvest-email-iriditrak
  - cronjobs/harvest-email-mp70
  - cronjobs/harvest-email-spot
  - cronjobs/harvest-tracertrak
  - cronjobs/harvest-tracplus
  - ingress.yaml
  - pdb.yaml
secretGenerator:
  - name: resourcetracking-env
    type: Opaque
    envs:
      - .env
generatorOptions:
  disableNameSuffixHash: true
labels:
  - includeSelectors: true
    pairs:
      variant: prod
patches:
  - path: deployment_patch.yaml
  - path: deployment_hpa_patch.yaml
  - path: service_patch.yaml
images:
  - name: ghcr.io/dbca-wa/resource_tracking
    newTag: 1.4.24
