bases:
- ../../base
nameSuffix: -prod
secretGenerator:
- name: resourcetracking-env
  envs:
  - .env
commonLabels:
  variant: prod
resources:
- service.yaml
- ingress.yaml
- cronjob_harvest_emails.yaml
patchesStrategicMerge:
- deployment_prod_patch.yaml
- statefulset_prod_patch.yaml
- persistentvolumeclaim_prod_patch.yaml
