apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: '*/2 * * * *'
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: resourcetracking-cronjob
              imagePullPolicy: IfNotPresent
              args: ['manage.py', 'harvest_tracertrak_feed']
              envFrom:
                - secretRef:
                    name: resourcetracking-env-prod
