apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: resourcetracking-cronjob
              imagePullPolicy: IfNotPresent
              args: ["manage.py", "harvest_tracertrak_feed"]
              env:
                - name: DATABASE_URL
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-prod
                      key: DATABASE_URL
                - name: TRACERTRAK_URL
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-prod
                      key: TRACERTRAK_URL
                - name: TRACERTRAK_AUTH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-prod
                      key: TRACERTRAK_AUTH_TOKEN
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: resourcetracking-env-prod
                      key: SENTRY_DSN
                - name: SENTRY_ENVIRONMENT
                  value: "prod"
