# Generated by Django 2.2.10 on 2020-03-04 01:03

from django.conf import settings
import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import radio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('comments', models.CharField(blank=True, max_length=512, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('comments', models.TextField(blank=True, max_length=512, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Repeater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=128)),
                ('last_inspected', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sss_display', models.BooleanField(default=True, verbose_name='SSS Display Enabled')),
                ('sss_description', models.CharField(blank=True, max_length=512, null=True)),
                ('channel_number', models.SmallIntegerField(blank=True, null=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('link_description', models.CharField(blank=True, max_length=512, null=True)),
                ('link_point', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('tx_frequency', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='TX Frequency (mHz)')),
                ('rx_frequency', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='RX Frequency (mHz)')),
                ('ctcss_tx', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='CTCSS TX (Hz)')),
                ('ctcss_rx', models.DecimalField(blank=True, decimal_places=8, max_digits=16, null=True, verbose_name='CTCSS RX (Hz)')),
                ('nac_tx', models.CharField(blank=True, max_length=32, null=True, verbose_name='NAC TX (P25)')),
                ('nac_rx', models.CharField(blank=True, max_length=32, null=True, verbose_name='NAC RX (P25)')),
                ('tx_antenna_height', models.FloatField(blank=True, null=True, verbose_name='TX Antenna Height (M)')),
                ('rx_antenna_height', models.FloatField(blank=True, null=True, verbose_name='RX Antenna Height (M)')),
                ('output_color', models.CharField(blank=True, max_length=32, null=True)),
                ('output_radius', models.FloatField(blank=True, null=True, verbose_name='Output Radius (Km)')),
                ('output_clutter', models.FloatField(blank=True, null=True, verbose_name='Output Clutter (M)')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='radio.District')),
                ('modifier', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('network', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='radio.Network')),
            ],
            options={
                'ordering': ['district__name', 'site_name'],
            },
        ),
        migrations.CreateModel(
            name='NetworkRXAnalysis',
            fields=[
                ('analyse_requested', models.DateTimeField(editable=False)),
                ('last_analysed', models.DateTimeField(editable=False, null=True)),
                ('last_downloaded', models.DateTimeField(editable=False, null=True)),
                ('analyse_result', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('raster_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_4326_file_path)),
                ('world_file_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_4326_file_path)),
                ('raster_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_mercator_file_path)),
                ('world_file_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_mercator_file_path)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), editable=False, null=True, size=4)),
                ('network', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rx_analysis', serialize=False, to='radio.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NetworkTXAnalysis',
            fields=[
                ('analyse_requested', models.DateTimeField(editable=False)),
                ('last_analysed', models.DateTimeField(editable=False, null=True)),
                ('last_downloaded', models.DateTimeField(editable=False, null=True)),
                ('analyse_result', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('raster_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_4326_file_path)),
                ('world_file_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_4326_file_path)),
                ('raster_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_mercator_file_path)),
                ('world_file_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.network_mercator_file_path)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), editable=False, null=True, size=4)),
                ('network', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tx_analysis', serialize=False, to='radio.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeaterTXAnalysis',
            fields=[
                ('analyse_requested', models.DateTimeField(editable=False)),
                ('last_analysed', models.DateTimeField(editable=False, null=True)),
                ('last_downloaded', models.DateTimeField(editable=False, null=True)),
                ('analyse_result', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('raster_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_4326_file_path)),
                ('world_file_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_4326_file_path)),
                ('raster_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_mercator_file_path)),
                ('world_file_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_mercator_file_path)),
                ('shp_file', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_shp_file_path)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), editable=False, null=True, size=4)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(editable=False, null=True, srid=4326)),
                ('repeater', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tx_analysis', serialize=False, to='radio.Repeater')),
                ('network', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeaterRXAnalysis',
            fields=[
                ('analyse_requested', models.DateTimeField(editable=False)),
                ('last_analysed', models.DateTimeField(editable=False, null=True)),
                ('last_downloaded', models.DateTimeField(editable=False, null=True)),
                ('analyse_result', django.contrib.postgres.fields.jsonb.JSONField(editable=False, null=True)),
                ('raster_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_4326_file_path)),
                ('world_file_4326', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_4326_file_path)),
                ('raster_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_mercator_file_path)),
                ('world_file_mercator', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_mercator_file_path)),
                ('shp_file', models.FileField(editable=False, max_length=512, null=True, storage=radio.models.OverwriteStorage(), upload_to=radio.models.repeater_shp_file_path)),
                ('bbox', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), editable=False, null=True, size=4)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(editable=False, null=True, srid=4326)),
                ('repeater', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rx_analysis', serialize=False, to='radio.Repeater')),
                ('network', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='radio.Network')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
