# Generated by Django 2.2.10 on 2020-03-04 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeater',
            name='site_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
