# Generated by Django 2.2.11 on 2020-03-05 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_auto_20200304_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repeaterrxanalysis',
            name='network',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='repeatertxanalysis',
            name='network',
            field=models.CharField(editable=False, max_length=64, null=True),
        ),
    ]
