# Generated by Django 2.2.11 on 2020-03-17 01:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_auto_20200312_0812'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepeaterTXCoverageSimplified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=128)),
                ('district', models.CharField(editable=False, max_length=64)),
                ('dn', models.IntegerField(editable=False, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(editable=False, null=True, srid=4326)),
                ('repeater', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='radio.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RepeaterRXCoverageSimplified',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=128)),
                ('district', models.CharField(editable=False, max_length=64)),
                ('dn', models.IntegerField(editable=False, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(editable=False, null=True, srid=4326)),
                ('repeater', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='radio.Repeater')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
