# Generated by Django 2.2.11 on 2020-03-18 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_repeaterrxcoveragesimplified_repeatertxcoveragesimplified'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeaterrxanalysis',
            name='last_merged',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repeaterrxanalysis',
            name='last_resolved',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repeaterrxanalysis',
            name='last_simplified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repeatertxanalysis',
            name='last_merged',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repeatertxanalysis',
            name='last_resolved',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='repeatertxanalysis',
            name='last_simplified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
