# Generated by Django 2.2.11 on 2020-03-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_auto_20200318_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeaterrxcoveragesimplified',
            name='color',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='repeatertxcoveragesimplified',
            name='color',
            field=models.CharField(editable=False, max_length=16, null=True),
        ),
    ]
