# Generated by Django 2.2.11 on 2020-03-25 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_auto_20200325_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkrxanalysis',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'Idle'), (110, 'Waiting to process'), (-122, 'Delete Failed'), (120, 'Waiting to delete'), (121, 'Deleting Calculation'), (129, 'Deleted Calculation'), (-132, 'Analyse Failed'), (130, 'Waiting to analyse'), (131, 'Analysing'), (139, 'Analysed'), (-142, 'Download Failed'), (140, 'Waiting to download'), (141, 'Downloading'), (149, 'Downloaded'), (-152, 'Extracting Failed'), (-153, 'Extract Required'), (150, 'Waiting to extract'), (151, 'Extrating Spatial Data'), (-9998, 'Timeout'), (-9999, 'Failed')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='networktxanalysis',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'Idle'), (110, 'Waiting to process'), (-122, 'Delete Failed'), (120, 'Waiting to delete'), (121, 'Deleting Calculation'), (129, 'Deleted Calculation'), (-132, 'Analyse Failed'), (130, 'Waiting to analyse'), (131, 'Analysing'), (139, 'Analysed'), (-142, 'Download Failed'), (140, 'Waiting to download'), (141, 'Downloading'), (149, 'Downloaded'), (-152, 'Extracting Failed'), (-153, 'Extract Required'), (150, 'Waiting to extract'), (151, 'Extrating Spatial Data'), (-9998, 'Timeout'), (-9999, 'Failed')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='repeaterrxanalysis',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'Idle'), (110, 'Waiting to process'), (-122, 'Delete Failed'), (120, 'Waiting to delete'), (121, 'Deleting Calculation'), (129, 'Deleted Calculation'), (-132, 'Analyse Failed'), (130, 'Waiting to analyse'), (131, 'Analysing'), (139, 'Analysed'), (-142, 'Download Failed'), (140, 'Waiting to download'), (141, 'Downloading'), (149, 'Downloaded'), (-152, 'Extracting Failed'), (-153, 'Extract Required'), (150, 'Waiting to extract'), (151, 'Extrating Spatial Data'), (-9998, 'Timeout'), (-9999, 'Failed')], default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='repeatertxanalysis',
            name='process_status',
            field=models.SmallIntegerField(choices=[(0, 'Idle'), (110, 'Waiting to process'), (-122, 'Delete Failed'), (120, 'Waiting to delete'), (121, 'Deleting Calculation'), (129, 'Deleted Calculation'), (-132, 'Analyse Failed'), (130, 'Waiting to analyse'), (131, 'Analysing'), (139, 'Analysed'), (-142, 'Download Failed'), (140, 'Waiting to download'), (141, 'Downloading'), (149, 'Downloaded'), (-152, 'Extracting Failed'), (-153, 'Extract Required'), (150, 'Waiting to extract'), (151, 'Extrating Spatial Data'), (-9998, 'Timeout'), (-9999, 'Failed')], default=0, editable=False),
        ),
    ]
