# Generated by Django 2.2.11 on 2020-03-26 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_auto_20200325_1552'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkrxanalysis',
            name='raster_mercator',
        ),
        migrations.RemoveField(
            model_name='networkrxanalysis',
            name='world_file_mercator',
        ),
        migrations.RemoveField(
            model_name='networktxanalysis',
            name='raster_mercator',
        ),
        migrations.RemoveField(
            model_name='networktxanalysis',
            name='world_file_mercator',
        ),
        migrations.RemoveField(
            model_name='repeaterrxanalysis',
            name='raster_mercator',
        ),
        migrations.RemoveField(
            model_name='repeaterrxanalysis',
            name='world_file_mercator',
        ),
        migrations.RemoveField(
            model_name='repeatertxanalysis',
            name='raster_mercator',
        ),
        migrations.RemoveField(
            model_name='repeatertxanalysis',
            name='world_file_mercator',
        ),
    ]
