# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=10, verbose_name='Financial Year')),
                ('fire_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='P&W Fire Number')),
                ('name', models.CharField(max_length=64, verbose_name='Incident Name')),
                ('incident_location', models.CharField(help_text="e.g. '10 km NE of Bridgetown' or 'Within the locality of Mitchell Plateau'", max_length=64, verbose_name='Location')),
                ('icc_location', models.TextField(blank=True, help_text='Address or location of Incident Control Centre', null=True, verbose_name='ICC Location')),
            ],
        ),
    ]
