# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_register', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=64)),
                ('surname', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=1)),
                ('date_of_birth', models.DateField()),
                ('agency', models.CharField(max_length=4)),
                ('occupational_position', models.CharField(max_length=128, verbose_name='Primary Occupational Position')),
                ('location_desc', models.CharField(max_length=128, verbose_name='Primary Occupational Location')),
                ('cost_centre', models.CharField(blank=True, max_length=10, null=True)),
                ('cost_centre_desc', models.CharField(blank=True, max_length=128, null=True)),
                ('mobile_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Phone No.')),
            ],
        ),
    ]
