# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_register', '0002_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_number', models.IntegerField()),
                ('shift_type', models.CharField(max_length=1)),
                ('accommodation_req', models.CharField(max_length=1, verbose_name='Accommodation Required?')),
                ('role_crew', models.CharField(max_length=128, verbose_name='Role at Incident or Crew Name')),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField()),
                ('accommodation_details', models.TextField(blank=True, null=True)),
                ('accommodation_time_to_travel', models.IntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shift_register.Employee')),
                ('incident', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='shift_register.Incident')),
            ],
        ),
    ]
