# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shift_register', '0003_employeeshift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_register.Employee'),
        ),
        migrations.AlterField(
            model_name='employeeshift',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shift_register.Incident'),
        ),
    ]
