# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-05 04:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shift_register', '0004_auto_20161005_1205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeshift',
            name='shift_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
