apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../../../template
nameSuffix: -harvest-iriditrak
patches:
- target:
    group: batch
    version: v1
    kind: CronJob
    name: resourcetracking-cronjob
  path: patch.yaml
