# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-08 08:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='humidity',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Relative humidity (%)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='pressure',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Pressure (hPa)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='temperature',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Temperature (\xb0Celcius)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='wind_direction',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Wind direction (\xb0 from N)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='wind_speed',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Wind speed (km/h)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weatherobservation',
            name='wind_speed_max',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Wind gust (km/h)', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='stay_connected',
            field=models.BooleanField(default=False, verbose_name='Persistent connection'),
        ),
    ]
