# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-28 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20160808_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherstation',
            name='manufacturer',
            field=models.CharField(blank=True, choices=[('telvent', 'Telvent'), ('vaisala', 'Vaisala')], max_length=100, null=True),
        ),
    ]
