# Generated by Django 2.1.11 on 2020-01-02 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_auto_20181212_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weatherobservation',
            name='actual_rainfall',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True),
        ),
    ]
