# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-19 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_weatherstation_manufacturer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weatherstation',
            name='stay_connected',
        ),
        migrations.AddField(
            model_name='weatherstation',
            name='upload_data',
            field=models.BooleanField(default=True, help_text='Upload observation data to external consumers (e.g. DAFWA)'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='abbreviation',
            field=models.CharField(help_text='Internal abbreviation code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='bom_abbreviation',
            field=models.CharField(help_text='Bureau of Meteorology site abbrevation code', max_length=4, unique=True, verbose_name='BoM abbreviation'),
        ),
        migrations.AlterField(
            model_name='weatherstation',
            name='ip_address',
            field=models.GenericIPAddressField(verbose_name='IPv4 address'),
        ),
    ]
