apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: ""
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: resourcetracking-cronjob
            image: ghcr.io/dbca-wa/resource_tracking
            imagePullPolicy: IfNotPresent
            command: ["python"]
            args: ["--version"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DATABASE_URL
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_HOST
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_PASSWORD
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: EMAIL_USER
            - name: DFES_PASS
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_PASS
            - name: DFES_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_URL
            - name: DFES_USER
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: DFES_USER
            - name: TRACPLUS_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-prod
                  key: TRACPLUS_URL
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
