apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: ""
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      parallelism: 1
      activeDeadlineSeconds: 300
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: resourcetracking-cronjob
            image: ghcr.io/dbca-wa/resource_tracking
            imagePullPolicy: IfNotPresent
            command: ["python"]
            args: ["--version"]
            securityContext:
              runAsNonRoot: true
              privileged: false
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: false
