# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 05:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20160808_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='district',
            field=models.CharField(blank=True, choices=[(1, 'Perth Hills'), (2, 'Swan Coastal'), (3, 'Blackwood'), (4, 'Wellington'), (5, 'Donnelly'), (6, 'Frankland'), (7, 'Albany'), (8, 'Esperance'), (9, 'East Kimberley'), (10, 'West Kimberley'), (11, 'Exmouth'), (12, 'Pilbara'), (13, 'Kalgoorlie'), (14, 'Geraldton'), (15, 'Moora'), (16, 'Shark Bay'), (17, 'Great Southern'), (18, 'Central Wheatbelt'), (19, 'Southern Wheatbelt')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
