# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20160811_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='symbol',
            field=models.CharField(choices=[('4 wheel drive passenger', '4-Wheel Drive Passenger'), ('4 wheel drive ute', '4-Wheel Drive (Ute)'), ('boat', 'Boat'), ('comms bus', 'Communications Bus'), ('dozer', 'Dozer'), ('fixed wing aircraft', 'Fixed-wing Aircraft'), ('float', 'Float'), ('gang truck', 'Gang Truck'), ('grader', 'Grader'), ('heavy duty', 'Heavy Duty'), ('light unit', 'Light Unit'), ('loader', 'Loader'), ('other', 'Other'), ('person', 'Person'), ('rotary aircraft', 'Rotary Aircraft'), ('snorkel', 'Snorkel'), ('tender', 'Tender')], default='Other', max_length=32),
        ),
    ]
