# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20160811_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='category',
        ),
        migrations.RemoveField(
            model_name='device',
            name='make',
        ),
        migrations.RemoveField(
            model_name='device',
            name='model',
        ),
        migrations.RemoveField(
            model_name='device',
            name='rego',
        ),
        migrations.AlterField(
            model_name='device',
            name='callsign',
            field=models.CharField(default='No Callsign', help_text='e.g. GT124, HD121', max_length=32, verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='No Name', help_text='e.g. 1QBB157', max_length=32, verbose_name='Rego'),
        ),
    ]
