# Generated by Django 2.1.11 on 2020-02-13 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20200102_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Hidden/private use'),
        ),
    ]
