# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_auto_20160812_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='callsign',
            field=models.CharField(default='No Vehicle ID', help_text='e.g. GT124, HD121', max_length=32, verbose_name='Vehicle ID'),
        ),
        migrations.AlterField(
            model_name='device',
            name='district',
            field=models.CharField(blank=True, choices=[('PHS', 'Perth Hills'), ('SWC', 'Swan Coastal'), ('BWD', 'Blackwood'), ('WTN', 'Wellington'), ('DON', 'Donnelly'), ('FRK', 'Frankland'), ('ALB', 'Albany'), ('ESP', 'Esperance'), ('EKM', 'East Kimberley'), ('WKM', 'West Kimberley'), ('EXM', 'Exmouth'), ('PIL', 'Pilbara'), ('KAL', 'Kalgoorlie'), ('GER', 'Geraldton'), ('MOR', 'Moora'), ('SHB', 'Shark Bay'), ('GSN', 'Great Southern'), ('CWB', 'Central Wheatbelt'), ('SWB', 'Southern Wheatbelt')], max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='No Rego', help_text='e.g. 1QBB157', max_length=32, verbose_name='Rego'),
        ),
    ]
