# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-11-01 00:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20160812_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='message',
            field=models.PositiveIntegerField(choices=[(1, 'Accessories Turned ON Message'), (2, 'Accessories Turned OFF Message'), (3, 'Tracking Message'), (5, 'Remote Polling Message'), (18, 'Emergency Message'), (19, 'Remote Command Acknowledge for Emergency Turn Off'), (25, 'Start Moving'), (26, 'Stop Moving')], default=3),
        ),
        migrations.AddField(
            model_name='loggedpoint',
            name='message',
            field=models.PositiveIntegerField(choices=[(1, 'Accessories Turned ON Message'), (2, 'Accessories Turned OFF Message'), (3, 'Tracking Message'), (5, 'Remote Polling Message'), (18, 'Emergency Message'), (19, 'Remote Command Acknowledge for Emergency Turn Off'), (25, 'Start Moving'), (26, 'Stop Moving')], default=3),
        ),
    ]
