# Generated by Django 2.2.11 on 2021-04-19 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20210119_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
    ]
