# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20161207_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='callsign',
            field=models.CharField(default='No RIN', help_text='e.g. HD123, GT456 or P789', max_length=32, verbose_name='Resource Identification Number (RIN)'),
        ),
        migrations.AlterField(
            model_name='device',
            name='district',
            field=models.CharField(blank=True, choices=[('PHS', 'Perth Hills'), ('SWC', 'Swan Coastal'), ('BWD', 'Blackwood'), ('WTN', 'Wellington'), ('DON', 'Donnelly'), ('FRK', 'Frankland'), ('ALB', 'Albany'), ('ESP', 'Esperance'), ('EKM', 'East Kimberley'), ('WKM', 'West Kimberley'), ('EXM', 'Exmouth'), ('PIL', 'Pilbara'), ('KAL', 'Kalgoorlie'), ('GER', 'Geraldton'), ('MOR', 'Moora'), ('SHB', 'Shark Bay'), ('GSN', 'Great Southern'), ('CWB', 'Central Wheatbelt'), ('SWB', 'Southern Wheatbelt'), ('AV', 'Aviation')], max_length=32, null=True),
        ),
    ]
