# Generated by Django 2.2.11 on 2021-04-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_invalidloggedpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='invalidloggedpoint',
            name='error_msg',
            field=models.TextField(default='N/A'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invalidloggedpoint',
            name='message',
            field=models.PositiveIntegerField(choices=[(1, 'Accessories Turned ON Message'), (2, 'Accessories Turned OFF Message'), (3, 'Tracking Message'), (5, 'Remote Polling Message'), (18, 'Emergency Message'), (19, 'Remote Command Acknowledge for Emergency Turn Off'), (25, 'Start Moving'), (26, 'Stop Moving')], default=3),
        ),
    ]
