# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20170105_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='contractor_details',
            field=models.CharField(blank=True, help_text='Person engaging contractor is responsible for maintaining contractor resource details', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_callsign',
            field=models.CharField(blank=True, help_text='e.g. FRK99', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='current_driver',
            field=models.CharField(blank=True, help_text='e.g. Jodie Jones', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='is_contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='device',
            name='usual_callsign',
            field=models.CharField(blank=True, help_text='e.g. DON99', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='usual_driver',
            field=models.CharField(blank=True, help_text='e.g. John Jones', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='usual_location',
            field=models.CharField(blank=True, help_text='e.g. Karijini National Park', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='No Rego', help_text='e.g. 1QBB157', max_length=32, verbose_name='Registration'),
        ),
    ]
