# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 05:43
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_auto_20170105_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rin_number',
            field=models.PositiveIntegerField(blank=True, help_text='Heavy Duty, Gang Truck or Plant only (HD/GT/P automatically prefixed). e.g. Entering 123 for a Heavy Duty will display as HD123, 456 for Gang Truck as GT456 and 789 for Plant as P789.', null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='Resource Identification Number (RIN)'),
        ),
    ]
