# Generated by Django 3.2.5 on 2021-10-17 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_device_fire_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='fire_type',
            field=models.BooleanField(default=None, null=True, verbose_name='Fire type'),
        ),
    ]
