# Generated by Django 3.2.5 on 2021-10-18 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_alter_device_fire_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='fire_type',
        ),
        migrations.AddField(
            model_name='device',
            name='fire_use',
            field=models.BooleanField(default=None, null=True, verbose_name='Fire use'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hidden',
            field=models.BooleanField(default=False, verbose_name='Visible to DFES'),
        ),
        migrations.AlterField(
            model_name='device',
            name='internal_only',
            field=models.BooleanField(default=False, verbose_name="'Visible on SSS"),
        ),
    ]
