# Generated by Django 3.2.5 on 2021-10-18 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_auto_20211019_0407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='internal_only',
            field=models.BooleanField(default=False, verbose_name='Visible on SSS'),
        ),
    ]
