# Generated by Django 3.2.5 on 2021-10-19 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0015_alter_device_internal_only'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='callsign',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
