# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 07:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_copy_data_to_other_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='callsign',
        ),
    ]
