# Generated by Django 3.2.16 on 2022-12-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0016_alter_device_callsign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Device hidden from DBCA resource tracking live view'),
        ),
        migrations.AlterField(
            model_name='device',
            name='internal_only',
            field=models.BooleanField(default=False, help_text='Device will only be shown on internal DBCA resource tracking live view (not to DFES, etc.)'),
        ),
    ]
