# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0017_remove_device_callsign'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AddField(
            model_name='loggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('other', 'Other')], default='other', max_length=32),
        ),
    ]
