# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-31 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20170131_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(default='No Rego', help_text='e.g. 1QBB157', max_length=7, verbose_name='Registration'),
        ),
    ]
