# Generated by Django 3.2.20 on 2023-09-11 00:17

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0018_auto_20230911_0744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loggedpoint',
            options={'ordering': ('-seen',)},
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(editable=False, srid=4326),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='raw',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='seen',
            field=models.DateTimeField(db_index=True, editable=False),
        ),
    ]
