# Generated by Django 3.2.20 on 2023-09-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0019_auto_20230911_0817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loggedpoint',
            name='raw',
            field=models.TextField(blank=True, editable=False, null=True),
        ),
    ]
