# Generated by Django 3.2.21 on 2023-10-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_alter_loggedpoint_raw'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InvalidLoggedPoint',
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'ordering': ('-seen',)},
        ),
        migrations.AlterField(
            model_name='device',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
