# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-01 03:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0020_auto_20170201_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='rin_display',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
