# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-02 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0021_device_rin_display'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='rin_display',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='RIN'),
        ),
    ]
