# Generated by Django 4.2.15 on 2024-09-02 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0022_resourceview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResourceView',
        ),
    ]
