# Generated by Django 4.2.15 on 2024-09-03 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0023_delete_resourceview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceid',
            field=models.CharField(help_text='Device unique identifier', max_length=128, unique=True, verbose_name='Device ID'),
        ),
    ]
