# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_auto_20170214_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.AddField(
            model_name='device',
            name='registration',
            field=models.CharField(default='No Rego', help_text='e.g. 1QBB157', max_length=32),
        ),
    ]
