# Generated by Django 4.2.18 on 2025-02-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_alter_device_deviceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration',
            field=models.CharField(default='No Rego', max_length=32),
        ),
    ]
