# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 04:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0024_auto_20170214_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='name',
            new_name='registration',
        ),
    ]
