# Generated by Django 4.2.20 on 2025-04-08 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_alter_device_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('netstar', 'Netstar'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('netstar', 'Netstar'), ('other', 'Other')], db_index=True, default='other', max_length=32),
        ),
    ]
