# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-16 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0025_create_tracking_view_for_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='registration',
            field=models.CharField(default='No Rego', help_text='e.g. 1QBB157', max_length=32),
        ),
    ]
