# Generated by Django 5.2.9 on 2025-12-11 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_alter_device_source_device_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='callsign_display',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='registration',
            field=models.CharField(default='No rego', max_length=32),
        ),
        migrations.AlterField(
            model_name='device',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('netstar', 'Netstar'), ('other', 'Other'), ('tracertrak', 'TracerTrak'), ('zoleo', 'Zoleo')], db_index=True, default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='loggedpoint',
            name='source_device_type',
            field=models.CharField(choices=[('tracplus', 'TracPlus'), ('iriditrak', 'Iriditrak'), ('dplus', 'DPlus'), ('spot', 'Spot'), ('dfes', 'DFES'), ('mp70', 'MP70'), ('fleetcare', 'Fleetcare'), ('netstar', 'Netstar'), ('other', 'Other'), ('tracertrak', 'TracerTrak'), ('zoleo', 'Zoleo')], db_index=True, default='other', max_length=32),
        ),
    ]
