# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 02:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0026_auto_20170616_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='usual_callsign',
        ),
    ]
