# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-04 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0029_auto_20170704_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='district_display',
            field=models.CharField(default='Other', max_length=100, verbose_name='District'),
        ),
    ]
