# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-22 00:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0030_create_tracking_views_for_layer'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='internal_only',
            field=models.BooleanField(default=False, verbose_name='Internal to DBCA only'),
        ),
    ]
