apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcetracking-deployment
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    spec:
      containers:
      - name: resourcetracking
        image: ghcr.io/dbca-wa/resource_tracking
        env:
        - name: ALLOWED_DOMAINS
          value: ".dbca.wa.gov.au"
        - name: CSRF_COOKIE_SECURE
          value: "True"
        - name: SESSION_COOKIE_SECURE
          value: "True"
        - name: TZ
          value: "Australia/Perth"
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "4096Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 5
        securityContext:
          runAsNonRoot: true
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: /tmp
            name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: "Memory"
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
