apiVersion: apps/v1
kind: Deployment
metadata:
  name: resourcetracking-deployment
  labels:
    app: resourcetracking-deployment
spec:
  selector:
    matchLabels:
      app: resourcetracking-deployment
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: resourcetracking-deployment
    spec:
      containers:
        - name: resourcetracking
          image: ghcr.io/dbca-wa/resource_tracking
          env:
            - name: ALLOWED_HOSTS
              value: '.dbca.wa.gov.au'
            - name: CSRF_TRUSTED_ORIGINS
              value: 'https://*.dbca.wa.gov.au'
            - name: CSRF_COOKIE_SECURE
              value: 'True'
            - name: SESSION_COOKIE_SECURE
              value: 'True'
            - name: TZ
              value: 'Australia/Perth'
          resources:
            requests:
              memory: '100Mi'
              cpu: '5m'
            limits:
              memory: '2Gi'
              cpu: '1000m'
          startupProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 3
            timeoutSeconds: 3
            successThreshold: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /livez
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8080
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
            timeoutSeconds: 5
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            privileged: false
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /tmp
              name: tmpfs-ram
      volumes:
        - name: tmpfs-ram
          emptyDir:
            medium: 'Memory'
      restartPolicy: Always
      terminationGracePeriodSeconds: 180
      automountServiceAccountToken: false
      tolerations:
        - key: arch
          operator: Equal
          value: arm64
          effect: NoSchedule
