apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: resourcetracking-db-statefulset
spec:
  replicas: 1
  template:
    spec:
      restartPolicy: Always
      volumes:
      - name: resourcetracking-pg14-data
        persistentVolumeClaim:
          claimName: resourcetracking-pg14-data
      initContainers:
      - name: resourcetracking-db-init
        image: postgis/postgis:14-3.1-alpine
        command:
        - /bin/bash
        - -c
        - mkdir -p /data/data; mkdir -p /data/archivedir; chown -R postgres:postgres /data
        volumeMounts:
        - mountPath: /data
          name: resourcetracking-pg14-data
      containers:
      - name: resourcetracking-db
        image: postgis/postgis:14-3.1-alpine
        args:
        - -c
        - max_connections=1000
        - -c
        - archive_mode=on
        - -c
        - archive_command=find /archivedir -mtime +7 -delete; lzma -c %p > /archivedir/%f.lzma
        env:
        - name: POSTGRES_USER
          value: resourcetracking
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: resourcetracking-pg14-data
          subPath: data
        - mountPath: /archivedir
          name: resourcetracking-pg14-data
          subPath: archivedir
        resources:
          requests:
            memory: "128Mi"
            cpu: "25m"
          limits:
            memory: "8192Mi"
            cpu: "1000m"
  updateStrategy:
    type: RollingUpdate
