apiVersion: batch/v1
kind: CronJob
metadata:
  name: resourcetracking-cronjob
spec:
  schedule: "* * * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: resourcetracking-cronjob
            args: ["manage.py", "harvest_tracking_email", "--device-type", "dplus"]
            env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: DATABASE_URL
            - name: EMAIL_HOST
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: EMAIL_HOST
            - name: EMAIL_USER
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: EMAIL_USER
            - name: EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: resourcetracking-env-uat
                  key: EMAIL_PASSWORD
